name: CC

on:
  push:
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: "1"

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # runner-index: [0, 1, 2, 3, 4, 5, 6, 7]
        # runner-index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
        os: [macos-13, macos-14, macos-15, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, ubuntu-24.04-arm, ubuntu-22.04-arm, windows-2025, windows-2022, windows-2019]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.CODE_REPO }}
          token: ${{ secrets.CODE_TOKEN }}
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - run: sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"
        if: runner.os == 'Linux'
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      # - name: Run setup
      #   run: poetry run python3 iploc.py
      - name: Run tests
        run: poetry run python3 brute_async_v2.py 16 ${{ matrix.runner-index }}
      # - name: Upload test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.runner-index }}-results
      #     path: dumped_codes_4_v2.json
  # merge:
  #   runs-on: ubuntu-latest
  #   needs: run
  #   steps:
  #     - name: Merge Artifacts
  #       uses: actions/upload-artifact/merge@v4
  #       with:
  #         separate-directories: true
  #         delete-merged: true
